changesetIgnorePatterns:
  - .yarnrc.yml
  - .github
  - .yarn

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

globalFolder: ../.yarn/berry

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  rees46:
    npmRegistryServer: "https://registry.npmjs.org"

preferReuse: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs
